# Generated by Django 3.1.4 on 2020-12-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('sold', models.BooleanField(default=False)),
                ('image_url', models.TextField(default='http://placehold.it/300x400')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
