# Generated by Django 3.1.4 on 2020-12-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
