# Generated by Django 3.1.4 on 2020-12-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(default=0.0, max_length=25),
        ),
    ]
